services:
  - docker

git:
  depth: 1

branches:
  only:
  - master

language: generic

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/sourcekit-lsp .
  - docker push $DOCKER_USERNAME/sourcekit-lsp

